# Generated by Django 5.2.8 on 2025-11-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_badge_alter_user_managers_handshake_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location_area',
            field=models.CharField(blank=True, help_text='General area for in-person services (e.g., Besiktas, Kadikoy)', max_length=100, null=True),
        ),
    ]
