# Generated by Django 5.2.8 on 2025-11-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_handshake_exact_location_duration'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['handshake', 'created_at'], name='api_chatmes_handsha_c8eac1_idx'),
        ),
        migrations.AddIndex(
            model_name='handshake',
            index=models.Index(fields=['service', 'status'], name='api_handsha_service_2a463e_idx'),
        ),
        migrations.AddIndex(
            model_name='handshake',
            index=models.Index(fields=['requester', 'status'], name='api_handsha_request_3f9338_idx'),
        ),
        migrations.AddIndex(
            model_name='handshake',
            index=models.Index(fields=['status', 'scheduled_time'], name='api_handsha_status_801358_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='api_notific_user_id_537f5a_idx'),
        ),
    ]
