# Generated by Django 5.2.8 on 2025-11-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chatmessage_api_chatmes_handsha_c8eac1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for approximate location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for approximate location', max_digits=9, null=True),
        ),
    ]
