# Generated by Django 5.2.8 on 2025-11-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_transaction_history'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(
                check=models.Q(timebank_balance__gte=-10.00),
                name='timebank_balance_minimum',
            ),
        ),
    ]
