# Generated by Django 5.2.8 on 2025-11-08 23:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fix_userbadge_uuid_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender'], name='api_chatmes_sender__7c187d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_handshake'], name='api_notific_related_964c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_service'], name='api_notific_related_7293ad_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='api_report_reporte_2c0738_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_user'], name='api_report_reporte_d53528_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_service'], name='api_report_reporte_f0e0eb_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['related_handshake'], name='api_report_related_45a3df_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['resolved_by'], name='api_report_resolve_27e31d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='api_report_status_2ddde8_idx'),
        ),
        migrations.AddIndex(
            model_name='reputationrep',
            index=models.Index(fields=['handshake'], name='api_reputat_handsha_11df71_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status', 'type', 'created_at'], name='api_service_status_350902_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['user', 'transaction_type', 'created_at'], name='api_transac_user_id_81158c_idx'),
        ),
    ]
