# Generated by Django 5.2.8 on 2025-11-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_reputation_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner_url',
            field=models.URLField(blank=True, max_length=500000, null=True),
        ),
    ]
