# Generated by Django 5.2.8 on 2025-11-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_increase_url_field_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
