# Generated by Django 5.2.9 on 2025-12-08 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_public_chat_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=2000)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NegativeRep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_late', models.BooleanField(default=False, help_text='Was late or no-show')),
                ('is_unhelpful', models.BooleanField(default=False, help_text='Was unhelpful or uncooperative')),
                ('is_rude', models.BooleanField(default=False, help_text='Was rude or disrespectful')),
                ('comment', models.TextField(blank=True, help_text='Optional explanation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='hot_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='Ranking score for hot/trending services'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status', '-hot_score'], name='api_service_status_746eb3_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent comment for replies (null for top-level comments)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.service'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='negativerep',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_negative_reps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='negativerep',
            name='handshake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negative_reps', to='api.handshake'),
        ),
        migrations.AddField(
            model_name='negativerep',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_negative_reps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['service', 'created_at'], name='api_comment_service_bab498_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'created_at'], name='api_comment_user_id_f11b09_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='api_comment_parent__be9ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['service', 'is_deleted', 'created_at'], name='api_comment_service_d1a5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='negativerep',
            index=models.Index(fields=['receiver', 'created_at'], name='api_negativ_receive_051934_idx'),
        ),
        migrations.AddIndex(
            model_name='negativerep',
            index=models.Index(fields=['giver', 'created_at'], name='api_negativ_giver_i_af3b53_idx'),
        ),
        migrations.AddIndex(
            model_name='negativerep',
            index=models.Index(fields=['handshake'], name='api_negativ_handsha_b0567e_idx'),
        ),
        migrations.AddConstraint(
            model_name='negativerep',
            constraint=models.UniqueConstraint(fields=('handshake', 'giver'), name='unique_negative_rep_per_handshake_giver'),
        ),
    ]
