# Generated by Django 5.2.9 on 2025-12-08 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_moderation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_verified_review',
            field=models.BooleanField(default=False, help_text='True if this is a post-completion verified review'),
        ),
        migrations.AddField(
            model_name='comment',
            name='related_handshake',
            field=models.ForeignKey(blank=True, help_text='Linked handshake for verified reviews', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_comments', to='api.handshake'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['related_handshake'], name='api_comment_related_507f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['service', 'is_verified_review'], name='api_comment_service_93bb78_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_verified_review', True)), fields=('related_handshake', 'user'), name='unique_verified_review_per_handshake_user'),
        ),
    ]
