# Generated by Django 5.2.9 on 2025-12-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_verified_review_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_verified_review_per_handshake_user',
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_verified_review', True)), fields=('related_handshake', 'user'), name='unique_verified_review_per_handshake_user'),
        ),
    ]
