# Generated by Django 5.2.9 on 2025-12-09 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_forum_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcategory',
            name='wikidata_tag',
            field=models.ForeignKey(blank=True, help_text='Optional Wikidata tag for semantic categorization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_categories', to='api.tag'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Wikidata tags for topic categorization', to='api.tag'),
        ),
    ]
