# Generated by Django 5.2.9 on 2025-12-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_featured_achievement_and_service_media'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicemedia',
            new_name='api_service_service_b5fef9_idx',
            old_name='api_servic_service_display_idx',
        ),
        migrations.RenameIndex(
            model_name='servicemedia',
            new_name='api_service_service_e2a400_idx',
            old_name='api_servic_service_media_t_idx',
        ),
    ]
