# Generated by Django 5.2.9 on 2025-12-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_account_lockout_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('no_show', 'No-Show Dispute'), ('inappropriate_content', 'Inappropriate Content'), ('service_issue', 'Service Issue'), ('spam', 'Spam'), ('scam', 'Scam or Fraud'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=25),
        ),
    ]
