"""
Django settings for hive_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'


def _is_truthy_env(name: str) -> bool:
    value = os.environ.get(name, '')
    return str(value).strip().lower() in {'1', 'true', 'yes', 'y', 'on'}


DJANGO_E2E = _is_truthy_env('DJANGO_E2E') or _is_truthy_env('E2E')

# Throttling controls
# - THROTTLE_RELAXED: keep throttling on, but raise limits to avoid UX issues for small deployments.
# - DISABLE_THROTTLING / NO_THROTTLE: bypass throttling entirely (use carefully).
_throttle_relaxed_explicit = os.environ.get('THROTTLE_RELAXED') is not None or os.environ.get('RELAX_THROTTLING') is not None
THROTTLE_RELAXED = (
    _is_truthy_env('THROTTLE_RELAXED')
    or _is_truthy_env('RELAX_THROTTLING')
    or (not _throttle_relaxed_explicit and not DEBUG)
)
DISABLE_THROTTLING = _is_truthy_env('DISABLE_THROTTLING') or _is_truthy_env('NO_THROTTLE')

SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-key-change-in-production'
    else:
        raise ValueError("SECRET_KEY environment variable must be set in production")

ALLOWED_HOSTS_STR = os.environ.get('ALLOWED_HOSTS')
if not ALLOWED_HOSTS_STR:
    ALLOWED_HOSTS = ['*'] if DEBUG else []
    if not DEBUG:
        raise ValueError("ALLOWED_HOSTS environment variable must be set for production")
else:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',')]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',  # GeoDjango for PostGIS spatial queries

    # 3rd Party Apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',
    'drf_spectacular',

    #Local Apps
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.RequestValidationMiddleware',
    'api.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'hive_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hive_project.wsgi.application'
ASGI_APPLICATION = 'hive_project.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database Configuration (uses environment variables from docker-compose.yml)
# Using PostGIS for geospatial queries
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': '5432',
    }
}

# Cache Configuration
# - In docker-compose, Redis is available and ensures DRF throttling is centralized.
# - Outside docker, fall back to local memory cache.
REDIS_HOST = os.environ.get('REDIS_HOST')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
REDIS_DB = os.environ.get('REDIS_DB', '1')
REDIS_URL = os.environ.get('REDIS_URL')

if REDIS_URL:
    _cache_location = REDIS_URL
elif REDIS_HOST:
    _cache_location = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
else:
    _cache_location = None

if _cache_location:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _cache_location,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'hive-locmem',
        }
    }

# Use new custom User model
AUTH_USER_MODEL = 'api.User'

# CORS Configuration
CORS_ALLOWED_ORIGINS_STR = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if CORS_ALLOWED_ORIGINS_STR:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_STR.split(',')]
else:
    # Default for development
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://localhost:5173",  # Vite default port
        "http://127.0.0.1:5173",
    ]

CORS_ALLOW_ALL_ORIGINS = False  # Never allow all
if DEBUG:
    # Allow localhost in development
    if not CORS_ALLOWED_ORIGINS_STR:
        CORS_ALLOWED_ORIGINS = [
            "http://localhost:3000",
            "http://localhost:5173",  # Vite default port
            "http://127.0.0.1:5173",
        ]
if not DEBUG and not CORS_ALLOWED_ORIGINS_STR:
    raise ValueError("CORS_ALLOWED_ORIGINS must be set for production")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,  # Increase from default 8
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads: videos, images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB max upload size
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'api.throttles.E2EAwareAnonRateThrottle',
        'api.throttles.E2EAwareUserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/hour',        # Reduced from 100/hour (REQ-NF-SEC-002)
        'user': '200/hour',       # Reduced from 1000/hour (REQ-NF-SEC-002)
        'registration': '20/hour',  # Separate rate for registration
        'handshake': '20/hour',   # Limit handshake creation
        'chat': '100/hour',       # Limit chat messages
        'confirm': '10/hour',     # Limit confirmations
        'sensitive': '10/hour',   # Rate limit for sensitive operations (password change, etc.)
        'reputation': '5/hour',    # Rate limit for reputation submissions
        'admin': '100/hour',      # Higher limit for admin operations
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'api.exceptions.custom_exception_handler',
}

# Relaxed throttling: for small/private deployments where UX matters more than strict abuse prevention.
# This keeps throttling enabled but effectively makes it "hard to hit" during normal usage.
if THROTTLE_RELAXED:
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        **REST_FRAMEWORK.get('DEFAULT_THROTTLE_RATES', {}),
        'anon': '500/hour',
        'user': '10000/hour',
        'registration': '200/hour',
        'handshake': '500/hour',
        'chat': '5000/hour',
        'confirm': '200/hour',
        'sensitive': '200/hour',
        'reputation': '200/hour',
        'admin': '1000/hour',
    }

# E2E mode: keep production/security defaults intact, but make automated tests deterministic.
# We still keep throttle classes enabled (E2E-aware wrappers will bypass), and bump rates
# as a safety net for any non-wrapped throttles.
if DJANGO_E2E:
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        **REST_FRAMEWORK.get('DEFAULT_THROTTLE_RATES', {}),
        'anon': '100000/hour',
        'user': '100000/hour',
        'registration': '100000/hour',
        'handshake': '100000/hour',
        'chat': '100000/hour',
        'confirm': '100000/hour',
        'sensitive': '100000/hour',
        'reputation': '100000/hour',
        'admin': '100000/hour',
    }

# Explicit throttle disable (overrides everything): used for local demos or tightly controlled deployments.
# Throttles will be bypassed by api.throttles.* classes when this is enabled.
if DISABLE_THROTTLING:
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        **REST_FRAMEWORK.get('DEFAULT_THROTTLE_RATES', {}),
        'anon': '1000000/hour',
        'user': '1000000/hour',
        'registration': '1000000/hour',
        'handshake': '1000000/hour',
        'chat': '1000000/hour',
        'confirm': '1000000/hour',
        'sensitive': '1000000/hour',
        'reputation': '1000000/hour',
        'admin': '1000000/hour',
    }

# Simple JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1 if not DEBUG else 24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7 if not DEBUG else 30),
    'ROTATE_REFRESH_TOKENS': True if not DEBUG else False,
    'BLACKLIST_AFTER_ROTATION': True if not DEBUG else False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

# Channels Configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(os.environ.get('REDIS_HOST', 'redis'), int(os.environ.get('REDIS_PORT', 6379)))],
        },
    },
}

# API Documentation (OpenAPI/Swagger)
SPECTACULAR_SETTINGS = {
    'TITLE': 'The Hive API',
    'DESCRIPTION': 'TimeBank economy platform API documentation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
